[build]
builder = "nixpacks"

[[services]]
name = "tourtastic-backend"
root_directory = "server"

[services.build]
builder = "nixpacks"
buildCommand = "npm install"

[services.deploy]
startCommand = "node server.js"
healthcheckPath = "/api/health"
restartPolicyType = "on_failure"

[[services]]
name = "tourtastic-frontend"
root_directory = "client"

[services.build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[services.deploy]
staticAssets = "dist"
