services:
  - type: web
    name: tourtastic
    env: node
    rootDir: server
    buildCommand: |
      # Install server dependencies
      npm install
      # Install and build client
      cd ../client
      npm install
      npm run build
      npm install
    startCommand: cd server && NODE_ENV=production npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false    healthCheckPath: /healthz
    buildFilter:
      paths:
        - client/**/*.{js,jsx,ts,tsx}
        - server/**/*.js
        - client/public/**/*
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
