services:
  - type: web
    name: tourtastic-backend
    env: node
    plan: starter # Ensures adequate resources
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /health # Added health check endpoint
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 8080
    scaling:
      minInstances: 1
      maxInstances: 1
    domains:
      - tourtastic-vxo1.onrender.com
